BEGIN {
  FS=","
  printf("#0 INQP, DEQP, 7QP, and NEWEQP joint database\n");
  printf("#1 Data collected and maintained by Claude VE2FK\n");
  printf("#2 Report updates and corrections directly to ve2fk@arrl.net\n");
  printf("#3 Last updated %s\n", strftime("%Y-%m-%d"));
}
{
  if ($0 ~ "!!Order!!") {
    if ($3 ~ /Exch1/) col = 2;
    if ($4 ~ /Exch1/) col = 3;
    if ($5 ~ /Exch1/) col = 4;
    printf("%s --> col=%d\n", $0, col) > "/dev/stderr";
  } 
  else {
    exch = $col

    if (exch ~ /^[A-Z]{5}\/[A-Z]{3}$/) {
      exch = substr(exch, 0, 6) substr(exch, 0, 2) substr(exch, 7);
      printf("%s --> %s\n", $0, exch) > "/dev/stderr";
    }

    state = exch ~ /^(DX|CT|MA|ME|NH|RI|VT|NJ|NY|DE|PA|MD|DC|AL|FL|GA|KY|NC|SC|TN|VA|AR|LA|MS|NM|OK|TX|CA|HI|AK|AZ|ID|MT|NV|OR|UT|WA|WY|MI|OH|WV|IL|WI|CO|IA|KS|MN|MO|ND|NE|SD)$/;
    prov = exch ~ /^(NL|NF|PE|NS|NB|QC|ON|MB|SK|AB|BC|NT|NU|YT)$/;
    incty = exch ~ /^(INADA|INALL|INBAR|INBEN|INBLA|INBOO|INBRO|INCAR|INCAS|INCLR|INCLY|INCLI|INCRA|INDAV|INDEA|INDEC|INDEK|INDEL|INDUB|INELK|INFAY|INFLO|INFOU|INFRA|INFUL|INGIB|INGRA|INGRE|INHAM|INHAN|INHAR|INHND|INHNR|INHOW|INHUN|INJAC|INJAS|INJAY|INJEF|INJEN|INJOH|INKNO|INKOS|INLAG|INLAK|INLAP|INLAW|INMAD|INMRN|INMRS|INMRT|INMIA|INMNR|INMNT|INMOR|INNEW|INNOB|INOHI|INORA|INOWE|INPAR|INPER|INPIK|INPOR|INPOS|INPUL|INPUT|INRAN|INRIP|INRUS|INSCO|INSHE|INSPE|INSTA|INSTE|INSTJ|INSUL|INSWI|INTPP|INTPT|INUNI|INVAN|INVER|INVIG|INWAB|INWRN|INWRK|INWAS|INWAY|INWEL|INWHT|INWHL)(\/(INADA|INALL|INBAR|INBEN|INBLA|INBOO|INBRO|INCAR|INCAS|INCLR|INCLY|INCLI|INCRA|INDAV|INDEA|INDEC|INDEK|INDEL|INDUB|INELK|INFAY|INFLO|INFOU|INFRA|INFUL|INGIB|INGRA|INGRE|INHAM|INHAN|INHAR|INHND|INHNR|INHOW|INHUN|INJAC|INJAS|INJAY|INJEF|INJEN|INJOH|INKNO|INKOS|INLAG|INLAK|INLAP|INLAW|INMAD|INMRN|INMRS|INMRT|INMIA|INMNR|INMNT|INMOR|INNEW|INNOB|INOHI|INORA|INOWE|INPAR|INPER|INPIK|INPOR|INPOS|INPUL|INPUT|INRAN|INRIP|INRUS|INSCO|INSHE|INSPE|INSTA|INSTE|INSTJ|INSUL|INSWI|INTPP|INTPT|INUNI|INVAN|INVER|INVIG|INWAB|INWRN|INWRK|INWAS|INWAY|INWEL|INWHT|INWHL))*$/;
    sevencnty = exch ~ /^(AZPMA|AZAPH|AZGLA|AZLPZ|AZNVO|AZSCZ|AZCHS|AZGHM|AZMCP|AZPMA|AZYVP|AZCNO|AZGLE|AZMHV|AZPNL|AZYMA|IDADA|IDBNV|IDCUS|IDKOO|IDOWY|IDADM|IDBOU|IDELM|IDLAT|IDPAY|IDBAN|IDBUT|IDFRA|IDLEM|IDPOW|IDBEA|IDCAM|IDFRE|IDLEW|IDSHO|IDBEN|IDCAN|IDGEM|IDLIN|IDTET|IDBIN|IDCAR|IDGOO|IDMAD|IDTWI|IDBLA|IDCAS|IDIDA|IDMIN|IDVAL|IDBOI|IDCLA|IDJEF|IDNEZ|IDWAS|IDBNR|IDCLE|IDJER|IDONE|MTBEA|MTFAL|MTLAK|MTPET|MTSHE|MTBIG|MTFER|MTLEW|MTPHI|MTSIL|MTBLA|MTFLA|MTLIB|MTPON|MTSTI|MTBRO|MTGAL|MTLIN|MTPWD|MTSWE|MTCRB|MTGAR|MTMAD|MTPWL|MTTET|MTCRT|MTGLA|MTMCC|MTPRA|MTTOO|MTCAS|MTGOL|MTMEA|MTRAV|MTTRE|MTCHO|MTGRA|MTMIN|MTRIC|MTVAL|MTCUS|MTHIL|MTMIS|MTROO|MTWHE|MTDAN|MTJEF|MTMUS|MTROS|MTWIB|MTDAW|MTJUD|MTPAR|MTSAN|MTYEL|MTDEE|NVCAR|NVELK|NVLAN|NVMIN|NVSTO|NVCHU|NVESM|NVLIN|NVNYE|NVWAS|NVCLA|NVEUR|NVLYO|NVPER|NVWHI|NVDOU|NVHUM|ORBAK|ORDES|ORJEF|ORMAL|ORUMA|ORBEN|ORDOU|ORJOS|ORMAR|ORUNI|ORCLK|ORGIL|ORKLA|ORMOR|ORWAL|ORCLT|ORGRA|ORLAK|ORMUL|ORWCO|ORCOL|ORHAR|ORLAN|ORPOL|ORWSH|ORCOO|ORHOO|ORLCN|ORSHE|ORWHE|ORCRO|ORJAC|ORLNN|ORTIL|ORYAM|ORCUR|UTBEA|UTDUC|UTKAN|UTSNJ|UTUTA|UTBOX|UTEME|UTMIL|UTSNP|UTWST|UTCAC|UTGAR|UTMOR|UTSEV|UTWSH|UTCAR|UTGRA|UTPIU|UTSUM|UTWAY|UTDAG|UTIRO|UTRIC|UTTOO|UTWEB|UTDAV|UTJUA|UTSAL|UTUIN|WAADA|WADOU|WAKLI|WAPAC|WASTE|WAASO|WAFER|WAKNG|WAPEN|WATHU|WABEN|WAFRA|WAKTP|WAPIE|WAWAH|WACHE|WAGAR|WAKTT|WASAN|WAWAL|WACLL|WAGRN|WALEW|WASKG|WAWHA|WACLR|WAGRY|WALIN|WASKM|WAWHI|WACOL|WAISL|WAMAS|WASNO|WAYAK|WACOW|WAJEF|WAOKA|WASPO|WYALB|WYCRO|WYLAR|WYPLA|WYTET|WYBIG|WYFRE|WYLIN|WYSHE|WYUIN|WYCAM|WYGOS|WYNAT|WYSUB|WYWAS|WYCAR|WYHOT|WYNIO|WYSWE|WYWES|WYCON|WYJOH|WYPAR)(\/(AZPMA|AZAPH|AZGLA|AZLPZ|AZNVO|AZSCZ|AZCHS|AZGHM|AZMCP|AZPMA|AZYVP|AZCNO|AZGLE|AZMHV|AZPNL|AZYMA|IDADA|IDBNV|IDCUS|IDKOO|IDOWY|IDADM|IDBOU|IDELM|IDLAT|IDPAY|IDBAN|IDBUT|IDFRA|IDLEM|IDPOW|IDBEA|IDCAM|IDFRE|IDLEW|IDSHO|IDBEN|IDCAN|IDGEM|IDLIN|IDTET|IDBIN|IDCAR|IDGOO|IDMAD|IDTWI|IDBLA|IDCAS|IDIDA|IDMIN|IDVAL|IDBOI|IDCLA|IDJEF|IDNEZ|IDWAS|IDBNR|IDCLE|IDJER|IDONE|MTBEA|MTFAL|MTLAK|MTPET|MTSHE|MTBIG|MTFER|MTLEW|MTPHI|MTSIL|MTBLA|MTFLA|MTLIB|MTPON|MTSTI|MTBRO|MTGAL|MTLIN|MTPWD|MTSWE|MTCRB|MTGAR|MTMAD|MTPWL|MTTET|MTCRT|MTGLA|MTMCC|MTPRA|MTTOO|MTCAS|MTGOL|MTMEA|MTRAV|MTTRE|MTCHO|MTGRA|MTMIN|MTRIC|MTVAL|MTCUS|MTHIL|MTMIS|MTROO|MTWHE|MTDAN|MTJEF|MTMUS|MTROS|MTWIB|MTDAW|MTJUD|MTPAR|MTSAN|MTYEL|MTDEE|NVCAR|NVELK|NVLAN|NVMIN|NVSTO|NVCHU|NVESM|NVLIN|NVNYE|NVWAS|NVCLA|NVEUR|NVLYO|NVPER|NVWHI|NVDOU|NVHUM|ORBAK|ORDES|ORJEF|ORMAL|ORUMA|ORBEN|ORDOU|ORJOS|ORMAR|ORUNI|ORCLK|ORGIL|ORKLA|ORMOR|ORWAL|ORCLT|ORGRA|ORLAK|ORMUL|ORWCO|ORCOL|ORHAR|ORLAN|ORPOL|ORWSH|ORCOO|ORHOO|ORLCN|ORSHE|ORWHE|ORCRO|ORJAC|ORLNN|ORTIL|ORYAM|ORCUR|UTBEA|UTDUC|UTKAN|UTSNJ|UTUTA|UTBOX|UTEME|UTMIL|UTSNP|UTWST|UTCAC|UTGAR|UTMOR|UTSEV|UTWSH|UTCAR|UTGRA|UTPIU|UTSUM|UTWAY|UTDAG|UTIRO|UTRIC|UTTOO|UTWEB|UTDAV|UTJUA|UTSAL|UTUIN|WAADA|WADOU|WAKLI|WAPAC|WASTE|WAASO|WAFER|WAKNG|WAPEN|WATHU|WABEN|WAFRA|WAKTP|WAPIE|WAWAH|WACHE|WAGAR|WAKTT|WASAN|WAWAL|WACLL|WAGRN|WALEW|WASKG|WAWHA|WACLR|WAGRY|WALIN|WASKM|WAWHI|WACOL|WAISL|WAMAS|WASNO|WAYAK|WACOW|WAJEF|WAOKA|WASPO|WYALB|WYCRO|WYLAR|WYPLA|WYTET|WYBIG|WYFRE|WYLIN|WYSHE|WYUIN|WYCAM|WYGOS|WYNAT|WYSUB|WYWAS|WYCAR|WYHOT|WYNIO|WYSWE|WYWES|WYCON|WYJOH|WYPAR))*$/;
    necnty = exch ~ /^(CTCAP|CTGBR|CTLCR|CTNAU|CTNOE|CTNOW|CTSOE|CTSOC|CTWES|MEAND|MEARO|MECUM|MEFRA|MEHAN|MEKEN|MEKNO|MELIN|MEOXF|MEPEN|MEPIS|MESAG|MESOM|MEWAL|MEWAS|MEYOR|MABAR|MABER|MABRI|MADUK|MAESS|MAFRA|MAHMD|MAHMP|MAMID|MANAN|MANOR|MAPLY|MASUF|MAWOR|NHBEL|NHCAR|NHCHE|NHCOO|NHGRA|NHHIL|NHMER|NHROC|NHSTR|NHSUL|RIBRI|RIKEN|RINEW|RIPRO|RIWAS|VTADD|VTBEN|VTCAL|VTCHI|VTESS|VTFRA|VTGRA|VTLAM|VTORA|VTORL|VTRUT|VTWAS|VTWNH|VTWND)(\/(CTCAP|CTGBR|CTLCR|CTNAU|CTNOE|CTNOW|CTSOE|CTSOC|CTWES|MEAND|MEARO|MECUM|MEFRA|MEHAN|MEKEN|MEKNO|MELIN|MEOXF|MEPEN|MEPIS|MESAG|MESOM|MEWAL|MEWAS|MEYOR|MABAR|MABER|MABRI|MADUK|MAESS|MAFRA|MAHMD|MAHMP|MAMID|MANAN|MANOR|MAPLY|MASUF|MAWOR|NHBEL|NHCAR|NHCHE|NHCOO|NHGRA|NHHIL|NHMER|NHROC|NHSTR|NHSUL|RIBRI|RIKEN|RINEW|RIPRO|RIWAS|VTADD|VTBEN|VTCAL|VTCHI|VTESS|VTFRA|VTGRA|VTLAM|VTORA|VTORL|VTRUT|VTWAS|VTWNH|VTWND))*$/;
    decnty = exch ~ /^[KNS]DE(\/([KNS]DE))?$/;

    if ($1 ~ /^[0-9A-Z/]+$/ && (state || prov || incty || sevencnty || necnty || decnty)) 
    {
      if (lines[$1] != "") {
        printf("\"%s\" reoccurs as \"%s\"\n", lines[$1], $0) > "/dev/stderr";
      }
      else if (!prov && exch !~ /\//)
      {
        # Skip county line entries and canadian provinces
        printf("%s=%s\n", $1, exch);
        lines[$1] = $0;
      }
    }
    else if ($0 !~ /^(!|#|$)/ && $col != "") 
    {
      printf("Ignored: \"%s\"\n", $0) > "/dev/stderr";
    }
  }
}