cp ../acqp/acqp.awk QSOP_AC/filter.awk
cp ../alqp/alqp.awk QSOP_AL/filter.awk
cp ../arqp/arqp.awk QSOP_AR/filter.awk
cp ../azqp/azqp.awk QSOP_AZ/filter.awk
cp ../bcqp/bcqp.awk QSOP_BC/filter.awk
cp ../caqp/caqp.awk QSOP_CA/filter.awk
cp ../coqp/coqp.awk QSOP_CO/filter.awk
cp ../cpqp/cpqp.awk QSOP_CP/filter.awk
cp ../flqp/flqp.awk QSOP_FL/filter.awk
cp ../gaqp/gaqp.awk QSOP_GA/filter.awk
cp ../hiqp/hiqp.awk QSOP_HI/filter.awk
cp ../iaqp/iaqp.awk QSOP_IA/filter.awk
cp ../idqp/idqp.awk QSOP_ID/filter.awk
cp ../ilqp/ilqp.awk QSOP_IL/filter.awk
cp ../ksqp/ksqp.awk QSOP_KS/filter.awk
cp ../kyqp/kyqp.awk QSOP_KY/filter.awk
cp ../laqp/laqp.awk QSOP_LA/filter.awk
cp ../mdqp/mdqp.awk QSOP_MDC/filter.awk
cp ../meqp/meqp.awk QSOP_ME/filter.awk
cp ../miqp/miqp.awk QSOP_MI/filter.awk
cp ../mnqp/mnqp.awk QSOP_MN/filter.awk
cp ../moqp/moqp.awk QSOP_MO/filter.awk
cp ../msqp/msqp.awk QSOP_MS/filter.awk
cp ../mtqp/mtqp.awk QSOP_MT/filter.awk
cp ../naqp/naqp.awk QSOP_NA/filter.awk
cp ../ncqp/ncqp.awk QSOP_NC/filter.awk
cp ../ndqp/ndqp.awk QSOP_ND/filter.awk
cp ../neqp/neqp.awk QSOP_NE/filter.awk
cp ../nhqp/nhqp.awk QSOP_NH/filter.awk
cp ../njqp/njqp.awk QSOP_NJ/filter.awk
cp ../nmqp/nmqp.awk QSOP_NM/filter.awk
cp ../nvqp/nvqp.awk QSOP_NV/filter.awk
cp ../nyqp/nyqp.awk QSOP_NY/filter.awk
cp ../ohqp/ohqp.awk QSOP_OH/filter.awk
cp ../okqp/okqp.awk QSOP_OK/filter.awk
cp ../onqp/onqp.awk QSOP_ON/filter.awk
cp ../paqp/paqp.awk QSOP_PA/filter.awk
cp ../qcqp/qcqp.awk QSOP_QC/filter.awk
cp ../scqp/scqp.awk QSOP_SC/filter.awk
cp ../sdqp/sdqp.awk QSOP_SD/filter.awk
cp ../tnqp/tnqp.awk QSOP_TN/filter.awk
cp ../txqp/txqp.awk QSOP_TX/filter.awk
cp ../vaqp/vaqp.awk QSOP_VA/filter.awk
cp ../vtqp/vtqp.awk QSOP_VT/filter.awk
cp ../waqp/waqp.awk QSOP_WA/filter.awk
cp ../wiqp/wiqp.awk QSOP_WI/filter.awk
cp ../wvqp/wvqp.awk QSOP_WV/filter.awk
cp ../in7qpnede/in7qpnede.awk QSOP_IN7QPNE_DE/filter.awk
