echo CAQP_db.txt > QSOP_CA/dbfile.txt
echo COQP_db.txt > QSOP_CO/dbfile.txt
echo CPQP_db.txt > QSOP_CP/dbfile.txt
echo FLQP_db.txt > QSOP_FL/dbfile.txt
echo GAQP_db.txt > QSOP_GA/dbfile.txt
echo HIQP_db.txt > QSOP_HI/dbfile.txt
echo IAQP_db.txt > QSOP_IA/dbfile.txt
echo IDQP_db.txt > QSOP_ID/dbfile.txt
echo ILQP_db.txt > QSOP_IL/dbfile.txt
echo IN7QPNEDE_db.txt > QSOP_IN7QPNE_DE/dbfile.txt
echo KSQP_db.txt > QSOP_KS/dbfile.txt
echo KYQP_db.txt > QSOP_KY/dbfile.txt
echo LAQP_db.txt > QSOP_LA/dbfile.txt
echo MDQP_db.txt > QSOP_MDC/dbfile.txt
echo MEQP_db.txt > QSOP_ME/dbfile.txt
echo MIQP_db.txt > QSOP_MI/dbfile.txt
echo MNQP_db.txt > QSOP_MN/dbfile.txt
echo MOQP_db.txt > QSOP_MO/dbfile.txt
echo MSQP_db.txt > QSOP_MS/dbfile.txt
echo MTQP_db.txt > QSOP_MT/dbfile.txt
echo NAQP_db.txt > QSOP_NA/dbfile.txt
echo NCQP_db.txt > QSOP_NC/dbfile.txt
echo NDQP_db.txt > QSOP_ND/dbfile.txt
echo NEQP_db.txt > QSOP_NE/dbfile.txt
echo NHQP_db.txt > QSOP_NH/dbfile.txt
echo NJQP_db.txt > QSOP_NJ/dbfile.txt
echo NMQP_db.txt > QSOP_NM/dbfile.txt
echo NVQP_db.txt > QSOP_NV/dbfile.txt
echo NYQP_db.txt > QSOP_NY/dbfile.txt
echo OHQP_db.txt > QSOP_OH/dbfile.txt
echo OKQP_db.txt > QSOP_OK/dbfile.txt
echo ONQP_db.txt > QSOP_ON/dbfile.txt
echo PAQP_db.txt > QSOP_PA/dbfile.txt
echo QCQP_db.txt > QSOP_QC/dbfile.txt
echo SCQP_db.txt > QSOP_SC/dbfile.txt
echo SDQP_db.txt > QSOP_SD/dbfile.txt
echo TNQP_db.txt > QSOP_TN/dbfile.txt
echo TXQP_db.txt > QSOP_TX/dbfile.txt
echo VAQP_db.txt > QSOP_VA/dbfile.txt
echo VTQP_db.txt > QSOP_VT/dbfile.txt
echo WAQP_db.txt > QSOP_WA/dbfile.txt
echo WIQP_db.txt > QSOP_WI/dbfile.txt
echo WVQP_db.txt > QSOP_WV/dbfile.txt
