BEGIN {
  FS=","
  printf("#0 URC DX RTTY prefill database\n");
  printf("#1 Data collected and maintained by Claude VE2FK\n");
  printf("#2 Report updates and corrections directly to ve2fk@arrl.net\n");
  printf("#3 Last updated %s\n", strftime("%Y-%m-%d"));
}
{
  if ($1 ~ /!!Order!!/) 
  {
    if ($3 ~ /Exch1|State/) col = 2;
    if ($4 ~ /Exch1|State/) col = 3;
    if ($5 ~ /Exch1|State/) col = 4;
    printf("\"%s\" --> col=%d\n", $0, col) > "/dev/stderr";
  } 
  else if ( \
    $1 ~ /^([A-Z1-9]+0?\/)?[1-9]?[A-Z]{1,2}[0-9]+[A-Z]+(\/[A-Z0-9]+)?$/ \
    && $col ~ /^(MOM|SPY|MCO|AGE|SBN|MRT|RDG|BOK|RMU|ANB|CFJ|CWY|EFJ|NFJ|RTM|WFJ|SWZ|TUN|GNA|BVT|PTR|AZJ|NCV|ADJ|GRA|SOS|ABK|MNO|SLK|ITU|UNO|UNS|VIC|WLB|TML|ISR|LBA|CYP|TNZ|ZAN|NGA|MGC|MAU|NGR|TGO|SMO|UGN|KNA|SGL|JMA|SOC|YMN|LSO|MLW|AGA|BAR|MDS|GYN|CRT|PGR|GHA|MTA|GZO|ZAM|KWT|SRL|JOH|KDH|KEL|MCA|NSL|PEN|PHG|PRK|PRL|SLG|TGU|LBN|SBH|SWK|NPL|DRC|BUN|SIG|RWD|TAT|BWN|MVA|TON|KUM|MSD|OMN|BHT|UAE|QTR|BHR|PAK|MSU|KMN|SBO|TWN|PSC|GRN|GSH|LIU|ORH|PRS|PJA|BJG|HLJ|JIL|LNG|HEB|IMG|SHX|TJN|JSU|SHD|SHG|FJN|JGX|ZJG|AHU|HBI|HEN|GGD|GGX|HNN|HUN|PCL|CQG|GZH|SCH|YNN|GSU|NGX|QGH|SHA|TBT|XIN|NUR|ADR|GBA|BHS|WMO|MBQ|ACM|AFS|TRP|CQM|VRS|SGO|MLE|OHG|BIO|ARU|LLS|AYS|MGL|ANT|EAS|DVT|JFZ|MRC|CUB|BLV|AGV|ATJ|CPT|LSB|NPT|MRA|SMI|SMG|TRC|GCS|SJR|PIC|FAL|FLS|CVO|UGY|SBL|SPL|ANG|CPV|CMR|BDB|BMN|BRL|BVR|BWG|HBG|HES|HGL|LSX|MWP|NRW|RLP|SAR|SWH|SXA|SXY|TRG|LZN|MDN|VIS|ETR|WBK|GAZ|NCK|SCK|NIU|BAH|BKO|SRP|AST|CRA|CSL|GLC|LRJ|AGN|BSQ|NVR|CTL|CLM|EXM|MRD|MCI|VCA|BRC|ADL|LPM|SOT|CEU|MLA|IRL|ARM|LIB|IRN|GGZ|TST|MLD|EST|HIU|SRE|ETP|MNC|MNR|BST|GDN|VTB|MOG|GML|BSK|CHY|BKN|OSH|NRN|ISK|TLS|JLA|MBK|KLB|QGT|SGD|DSB|TJT|AHL|BLN|MRY|DGZ|LBP|ABD|ALS|AQE|AVG|BRG|BRT|CEN|CHA|FCM|IDF|LMS|LNM|LRN|LRS|MPS|NPC|PAC|PCD|PCH|PLO|RAP|UNM|GLO|MYT|SBT|CHF|LYT|NCL|MTQ|ATL|BAS|CPN|GMB|MQS|STY|TMT|MQL|SPR|BSI|EPA|GSO|JDN|RUN|TLN|SMN|CZT|KGN|AIE|AMD|SPU|FUT|WAL|FGU|EML|ESE|GLN|NEE|NWE|SEE|SLY|SWE|WGT|WML|YAH|IOM|NIR|JRS|HIL|NIH|ORK|RCL|SCO|SHL|SIH|SKD|WIS|ANY|GNY|WLS|SOL|TEM|HGR|SZL|LTS|ECD|GPG|HAI|DMR|CBA|BJN|MLP|PVD|RNC|SAN|SEO|GWN|GYE|ICH|DJN|NCG|SCG|GJU|HKS|JJU|NJL|SJL|BUS|DGU|NGN|SGN|ULN|USN|PAN|HON|SNL|CTH|ETH|ISN|NTH|SET|VTC|SAI|LIG|PMT|LBY|VTO|ERO|TSC|ABZ|MCH|APU|BSL|CBR|CMP|MSE|PLG|PTL|TAA|LZO|UBA|SRA|SIC|FVG|AVL|DJB|GND|GBS|SLC|DMC|SVG|CHB|GNM|IBI|IZU|KWA|STA|TCI|TYO|YSH|AHA|GFU|MIE|SKA|HYO|KYO|NAR|OSA|SHI|WYA|HRM|OKI|OYA|SME|TOT|YMG|EHM|KCI|KGW|TMA|AMI|FKA|GOT|IKI|KGS|KMT|MZK|NGS|OIT|OSU|SAG|TOK|TSU|AKI|AOM|FSM|IWA|MYG|YAM|HKD|FKI|ISH|TOY|NGO|NIG|SAD|MTI|OGW|OTI|VLC|DTO|OKW|SKM|MNL|BER|SVD|JMN|JOR|CNT|MIN|MST|NHM|RHO|VMT|NJR|NYO|DCO|DLW|MRL|PVN|ALA|FLA|GEA|KCY|NCR|SCR|TNS|VGN|AKS|LSA|MSP|NMX|OKH|TXS|CAL|AZA|IHO|MNA|NVA|ORN|UTA|WTN|WYM|MIC|OHO|WVG|ILN|IND|WSC|ANV|SOP|GTO|BKE|HWL|GUM|JHN|MDW|JVS|PLM|KGM|HWI|KUR|ASM|RSE|SWN|WAK|MAR|ALK|ALU|CLR|IOW|KNS|MIS|MNS|NBR|NDK|SDK|NAV|UVI|PRC|DSC|NNR|SNR|BAD|BAP|SFE|CHC|FMS|CDB|MSN|ERS|TUC|CRN|MZA|SDE|SLT|SJU|SLU|CMC|LRO|JUJ|LPA|RNE|CHT|SCZ|TDF|NQN|LUX|LIT|SBU|NBU|PRU|LEB|VNA|SZG|LAU|BGL|UAU|STR|TRL|CTA|VBG|EFL|SFL|WFL|OLU|LAP|ALD|MKT|BHE|MOR|SLA|BRS|FDS|WLN|GRE|FAR|BRM|CHG|CJU|NJU|SDM|ZEL|PNG|ABA|NKO|NTL|CCO|BRE|SEU|SAB|SIM|ESO|GOS|SCN|SGP|AGO|AMZ|TOS|APA|PBA|MHO|RGN|PIU|BFD|CER|ACR|MGS|RRM|RDA|RDJ|SPO|RGS|MNG|PNA|BHA|PBC|PRA|MGR|ABH|FDN|MVZ|RCS|SPP|TRI|SUR|FJL|VRA|BGD|SLV|SEY|PCP|STM|GTL|NSN|MSW|WSW|ESW|SWS|OLD|SSW|SHM|WSA|WPM|KPA|PMR|GPL|LBZ|PDL|WAM|MSA|LSL|OPL|HCS|LDZ|LBL|SCP|LPL|SLS|SUD|EGY|SII|ATC|CGR|MAT|MCD|PPN|TSL|DDC|ERU|WTR|CHS|CYC|ION|LBS|SMS|CTE|TUV|PHX|LIN|BNB|GBT|SML|SMA|PLU|SON|ETC|NWA|WAN|SWA|SCA|NCA|NEA|SEA|EAN|GKA|ICL|GUA|CRI|COC|CMN|CSI|CAF|ROC|GBN|CHD|CIV|BNN|MLI|KLN|SPB|GGL|LEN|KAR|ARK|NZM|SOV|KGV|NNT|VAY|VOL|NVG|PSK|MUR|KAL|MSC|MSR|ORL|LPK|TVR|SLN|YAR|KSM|TUL|VOR|TAM|RZN|NNV|IVO|VLR|KRK|KGA|BRK|BLG|VGD|STV|PNZ|SMR|ULK|KRV|TTS|MEL|MDV|UDM|CHU|KDR|KCH|SVL|KKT|NOA|CMA|RTV|CHN|IGS|SVT|ASN|DGS|KAB|ADY|CLB|SDL|PRM|KPM|TOM|KHM|YAN|TYU|OMS|NOV|KRG|OBG|KVO|BSH|KOM|ALT|RAL|KRA|NOR|SZM|TMR|KHB|JWS|KRL|SKL|EVN|MGD|AMU|CHK|WGL|PMO|BUR|NSB|SAK|IRK|CHI|KSA|KAK|TYV|COM|KMA|TOC|TOR|QQD|SRD|AJN|FGN|SQD|BHO|NMN|NVY|SDO|KZM|JZH|QPS|MGU|AQA|ASA|NKZ|PVR|AMC|AQT|EKZ|QZO|QTY|WKZ|SKZ|ATU|QGY|AMR|BKR|ZBL|SUM|TNP|CSY|TCP|DPT|ODE|KHN|PVA|DNK|RVN|KHA|LUH|VIN|VLN|ZAP|CNH|IFR|KHL|KVR|KRO|LVV|ZHM|CHV|MYV|KVC|ATG|BRB|RDN|BLZ|NEV|SKS|NMB|PGN|CUK|KSR|POH|YAP|MSH|BDS|NSC|QBC|ONT|MTB|SKW|ABT|BCO|NWT|NBW|ACT|JBT|NSW|VIA|QLD|SAU|WAU|TAS|NOT|AAC|COS|EMR|LHW|MLL|NFK|LIH|WIL|CMS|BAC|HRD|MCQ|NFL|LBR|AGL|SBR|MOS|ADA|BVI|TAC|DUC|HED|OEN|PIT|ADE|ALX|FKL|SGE|SOR|SSA|SSH|BMD|CGS|HKG|ANP|ARP|ASS|BIH|CDH|CTG|DAD|DEL|DNH|GJT|GOA|HIP|HYA|JAK|JRD|KLA|KTK|MDP|MHL|MHR|MPR|MZM|NGL|ORS|PJB|PUD|RJN|SIK|TAN|TPU|UTP|UTR|WBL|ADM|LSD|MCY|NCB|YKN|PEI|NVT|CMX|NOM|SMX|AJS|GLP|ACS|TRO|ACN|CAN|RGG|BUF|CAM|NVM|SVM|LAO|MAO|MYA|TNH|AFG|BTN|WJA|CJA|YKT|EJA|BBG|BLU|JMB|LPG|SSU|RIA|RII|WSU|ACH|NSM|CKN|EKN|SKN|WKN|CSW|GTA|MKU|NMK|NSU|SES|SSL|WSL|BAL|ENT|PPA|WNT|WPP|JTA|IRQ|KRD|VNU|SYR|LAT|NIC|COR|WRO|BUC|SER|NWR|CRO|SWR|NER|SRO|ESL|SRB|VOJ|FLC|TJL|ZUL|BNS|MDA|TCR|LAR|PTS|YRC|ARG|CBO|CJD|CCS|GCO|MIR|VGS|AGU|BOL|NVE|SUC|DAM|MON|APE|AZS|AVE|BQL|LAA|LFA|LHA|LRA|LTU|OCL|ZIM|NMA|KOS|SSD|ALB|GIB|AKR|DHE|SHE|ASC|GOU|TDC|CYM|TLU|NIN|NIS|SIN|SIS|BLY|ROS|SCT|ATP|BOU|CTM|KDC|ACL|CBL|SRS|PAR|ECP|WCP|NCP|FRS|KZN|GAU|LPO|MPU|NOW|SAA|MRN|PED)$/) 
  {
    if (lines[$1] != "") 
    {
      printf("\"%s\" reoccurs as \"%s\"\n", lines[$1], $0) > "/dev/stderr";
    }
    else 
    {
      printf("%s=%s\n", $1, $col);
      lines[$1] = $0;
    }
  }
  else if ($0 !~ /^(!|#|$)/ && $col != "") 
  {
    printf("Bad exchange: \"%s\"\n", $0) > "/dev/stderr";
  } 
}
