BEGIN {
  FS=","
}
{
  if ($3 ~ /^(ANDME|AROME|CUMME|FRAME|HANME|KENME|KNOME|LINME|OXFME|PENME|PISME|SAGME|SOMME|WALME|WASME|YORME|BARMA|BERMA|BRIMA|DUKMA|ESSMA|FRAMA|HMDMA|HMPMA|MIDMA|NANMA|NORMA|PLYMA|SUFMA|WORMA|BELNH|CARNH|CHENH|COONH|GRANH|HILNH|MERNH|ROCNH|STRNH|SULNH|BRIRI|KENRI|NEWRI|PRORI|WASRI|ADDVT|BENVT|CALVT|CHIVT|ESSVT|FRAVT|GRAVT|LAMVT|ORAVT|ORLVT|RUTVT|WASVT|WNHVT|WNDVT)$/) {
    exch = substr($3, 4, 2) substr($3, 1, 3);
    printf("%s,,%s,\n", $1, exch);
  } else if ($0 ~ /^(!|#|$)/) {
    printf("%s\n", $0);
  } else if ($3 !~ /(FAICT|HARCT|LITCT|MIDCT|NHVCT|NLNCT|TOLCT|WINCT)/ && $3 !~ /^$/) {
    printf("%s,,%s,\n", $1, $3);
  }
}